services:
  app:
    container_name: semanttuli-v2
    image: semanttuli-v2
    build:
      context: .
      dockerfile: Dockerfile
    user: 'node'
    environment:
      - NODE_ENV=production
      - TZ=Europe/Helsinki
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3