# fly.toml file generated for semanttuli on 2022-09-28T21:22:55+03:00

app = "semanttuli"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  MONGO_CONNECTION_STRING = "${MONGO_CONNECTION_STRING}"
  DB_NAME = "${DB_NAME}"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
